defmodule Mix.Tasks.Harness.Clean do
  @shortdoc "Removes files generated by harness"
  @moduledoc """
  Removes links, files, and directories generated by harness
  """

  use Mix.Task

  alias Harness.{Manifest, Renderer}

  @impl Mix.Task
  def run(_args) do
    path = "."

    Mix.Task.run("harness.compile", [path])

    Manifest.load(path)

    Renderer.clean(path)
  end
end
